Embedded.

diff --git a/.azure/pipelines/components-e2e-tests.yml b/.azure/pipelines/components-e2e-tests.yml
--- a/.azure/pipelines/components-e2e-tests.yml
+++ b/.azure/pipelines/components-e2e-tests.yml
@@ -58,7 +58,25 @@ jobs:
       displayName: Build JS
     - script: .dotnet/dotnet build ./src/Components/test/E2ETest -c $(BuildConfiguration) --no-restore
       displayName: Build
-    - bash: ./eng/scripts/run-unquarantined-e2e-tests.sh $(BuildConfiguration) $(Build.SourcesDirectory)
+    - script: |
+        set -o pipefail
+
+        .dotnet/dotnet test ./src/Components/test/E2ETest \
+          -c $(BuildConfiguration) \
+          --no-build \
+          --filter 'Quarantined!=true|Quarantined=false' \
+          -p:VsTestUseMSBuildOutput=false \
+          --logger:"trx%3BLogFileName=Microsoft.AspNetCore.Components.E2ETests.trx" \
+          --logger:"html%3BLogFileName=Microsoft.AspNetCore.Components.E2ETests.html" \
+          --results-directory $(Build.SourcesDirectory)/artifacts/TestResults/$(BuildConfiguration)/Unquarantined \
+          | tee e2e-test-output.log
+
+        if grep -q "No test matches the given testcase filte" e2e-test-output.log
+        then
+          echo "##vso[task.logissue type=error] No tests matched the filter string was found in output."
+
+          exit 1
+        fi
       displayName: Run E2E tests
     - script: .dotnet/dotnet test ./src/Components/test/E2ETest -c $(BuildConfiguration) --no-build --filter 'Quarantined=true' -p:RunQuarantinedTests=true
                  -p:VsTestUseMSBuildOutput=false
