test coreCLR WASM

diff --git a/.azure/pipelines/components-e2e-tests.yml b/.azure/pipelines/components-e2e-tests.yml
--- a/.azure/pipelines/components-e2e-tests.yml
+++ b/.azure/pipelines/components-e2e-tests.yml
@@ -49,10 +49,11 @@ variables:
 - template: /eng/common/templates/variables/pool-providers.yml
 
 jobs:
+# Mono runtime (default) E2E tests
 - template: jobs/default-build.yml
   parameters:
     jobName: Components_E2E_Test
-    jobDisplayName: "Test: Blazor E2E tests on Linux"
+    jobDisplayName: "Test: Blazor E2E tests on Linux (Mono)"
     agentOs: Linux
     use1ESUbuntu: true
     isAzDOTestingJob: true
@@ -112,7 +113,7 @@ jobs:
         testResultsFormat: 'VSTest'
         testResultsFiles: '*.trx'
         searchFolder: '$(Build.SourcesDirectory)/artifacts/TestResults/$(BuildConfiguration)/Unquarantined'
-        testRunTitle: ComponentsE2E-$(AgentOsName)-$(BuildConfiguration)-xunit
+        testRunTitle: ComponentsE2E-Mono-$(AgentOsName)-$(BuildConfiguration)-xunit
       condition: always()
     - task: PublishTestResults@2
       displayName: Publish Quarantined E2E Test Results
@@ -120,7 +121,7 @@ jobs:
         testResultsFormat: 'VSTest'
         testResultsFiles: '*.trx'
         searchFolder: '$(Build.SourcesDirectory)/artifacts/TestResults/$(BuildConfiguration)/Quarantined'
-        testRunTitle: Quarantine-$(AgentOsName)-$(BuildConfiguration)-xunit
+        testRunTitle: Quarantine-Mono-$(AgentOsName)-$(BuildConfiguration)-xunit
         mergeTestResults: true
       condition: always()
 
@@ -130,6 +131,93 @@ jobs:
       publishOnError: true
       includeForks: true
     - name: Components_E2E_Test_Logs
+      path: '$(Build.SourcesDirectory)/artifacts/TestResults/$(BuildConfiguration)'
+      includeForks: true
+      publishOnError: true
+
+# CoreCLR runtime E2E tests (UseMonoRuntime=false)
+- template: jobs/default-build.yml
+  parameters:
+    jobName: Components_E2E_Test_CoreCLR
+    jobDisplayName: "Test: Blazor E2E tests on Linux (CoreCLR)"
+    agentOs: Linux
+    use1ESUbuntu: true
+    isAzDOTestingJob: true
+    enablePublishTestResults: false
+    timeoutInMinutes: 120
+    steps:
+    - script: git submodule update --init
+      displayName: Update submodules
+    - script: ./restore.sh
+      displayName: Run restore.sh
+    - script: npm ci
+      displayName: NPM install
+    - script: npm run build
+      displayName: Build JS
+    - script: .dotnet/dotnet build ./src/Components/test/E2ETest -c $(BuildConfiguration) /p:UseMonoRuntime=false
+      displayName: Build (CoreCLR)
+    - script: |
+        set -eo pipefail
+
+        # Only run WASM-relevant tests; skip Server and SSR tests since UseMonoRuntime only affects WASM.
+        .dotnet/dotnet test ./src/Components/test/E2ETest \
+          -c $(BuildConfiguration) \
+          --no-build \
+          --filter 'Quarantined!=true&FullyQualifiedName!~ServerExecutionTest&FullyQualifiedName!~ServerRenderingTest' \
+          -p:VsTestUseMSBuildOutput=false \
+          --logger:"trx%3BLogFileName=Microsoft.AspNetCore.Components.E2ETests.trx" \
+          --logger:"html%3BLogFileName=Microsoft.AspNetCore.Components.E2ETests.html" \
+          --results-directory $(Build.SourcesDirectory)/artifacts/TestResults/$(BuildConfiguration)/Unquarantined \
+          | tee e2e-test-output.log
+
+        if grep -q "No test matches the given testcase filter" e2e-test-output.log
+        then
+          echo "##vso[task.logissue type=error] No tests matched the filter."
+
+          exit 1
+        fi
+
+        # Check total tests run to detect abnormalities. In case the number of tests changes significantly, we should adjust the threshold.
+        # Extract total from the summary line "Failed: xx, Passed: yy, Skipped: zz, Total: NNN, Duration: ..."
+        total=$(sed -nE 's/.*Failed:[[:space:]]*[0-9]+,[[:space:]]*Passed:[[:space:]]*[0-9]+,[[:space:]]*Skipped:[[:space:]]*[0-9]+,[[:space:]]*Total:[[:space:]]*([0-9]+).*/\1/p' e2e-test-output.log)
+        min_total=600
+        if [ -z "$total" ] || [ "$total" -lt "$min_total" ]
+        then
+          echo "##vso[task.logissue type=error] Insufficient total test count: $total. We expect at least $min_total tests to run."
+          exit 1
+        fi
+      displayName: Run E2E tests (CoreCLR)
+    - script: .dotnet/dotnet test ./src/Components/test/E2ETest -c $(BuildConfiguration) --no-build --filter 'Quarantined=true&FullyQualifiedName!~ServerExecutionTest&FullyQualifiedName!~ServerRenderingTest' -p:RunQuarantinedTests=true
+                 -p:VsTestUseMSBuildOutput=false
+                 --logger:"trx%3BLogFileName=Microsoft.AspNetCore.Components.E2ETests.trx"
+                 --logger:"html%3BLogFileName=Microsoft.AspNetCore.Components.E2ETests.html"
+                 --results-directory $(Build.SourcesDirectory)/artifacts/TestResults/$(BuildConfiguration)/Quarantined
+      displayName: Run Quarantined E2E tests (CoreCLR)
+      continueOnError: true
+    - task: PublishTestResults@2
+      displayName: Publish E2E Test Results (CoreCLR)
+      inputs:
+        testResultsFormat: 'VSTest'
+        testResultsFiles: '*.trx'
+        searchFolder: '$(Build.SourcesDirectory)/artifacts/TestResults/$(BuildConfiguration)/Unquarantined'
+        testRunTitle: ComponentsE2E-CoreCLR-$(AgentOsName)-$(BuildConfiguration)-xunit
+      condition: always()
+    - task: PublishTestResults@2
+      displayName: Publish Quarantined E2E Test Results (CoreCLR)
+      inputs:
+        testResultsFormat: 'VSTest'
+        testResultsFiles: '*.trx'
+        searchFolder: '$(Build.SourcesDirectory)/artifacts/TestResults/$(BuildConfiguration)/Quarantined'
+        testRunTitle: Quarantine-CoreCLR-$(AgentOsName)-$(BuildConfiguration)-xunit
+        mergeTestResults: true
+      condition: always()
+
+    artifacts:
+    - name: Components_E2E_CoreCLR_Logs
+      path: artifacts/log/
+      publishOnError: true
+      includeForks: true
+    - name: Components_E2E_CoreCLR_Test_Logs
       path: '$(Build.SourcesDirectory)/artifacts/TestResults/$(BuildConfiguration)'
       includeForks: true
       publishOnError: true
